### ISSUE TITLE
[BUG] Issue to conversion workflow starts but does not finish.

### ISSUE THREAD

**Issue by Remi-Gau** [brainhackorg/global2021#78]
See the report here.

https://github.com/brainhackorg/global2021/runs/4178661874?check_suite_focus=true

@jhlegarreta pinging you but I can try to start debugging a bit later.

**Comment by jhlegarreta** [comment]
A few notes:
- I had already observed this. Cross-referencing https://github.com/brainhackorg/global2021/pull/72#issuecomment-963754572.
- As mentioned in the cross-referenced comment, when one tries the script (as provided by the refactoring in PR #72) with the following changes (I had to test on the 2020 repository since there were no projects when I made the changes): 
  - Make the URL point to the 2020 repository.
  - Change the project repository regex in https://github.com/brainhackorg/global2021/blob/6106d92623711d22b6818e5d67f63b74cf15b9f2/scripts/issues_to_pages.py#L204 to `Link to the project` to account for the change in the section name of the template
  - Changes the filter in here https://github.com/brainhackorg/global2021/blob/6106d92623711d22b6818e5d67f63b74cf15b9f2/scripts/issues_to_pages.py#L251 to `status:published `, and moves the `proj_url_re_match.group()` block in https://github.com/brainhackorg/global2021/blob/d46594d9d7c62809b07a674d5794ef81b4dfef8e/scripts/issues_to_pages.py#L207 inside the `if` to avoid accessing the `group` member in case of `None`s,

  the script does its job. I know, too many things to make it work with the 2020 repository, but it works. So I thought there was something else that made the script hang.
- I did not have a clear idea of what was going on, and assumed the changes in the mentioned PR were not introducing that bug, since I was able to run it successfully with the changes above.

Some testing shows that the script gets stuck precisely in https://github.com/brainhackorg/global2021/blob/6106d92623711d22b6818e5d67f63b74cf15b9f2/scripts/issues_to_pages.py#L204, the `issue["body"]` contains the issue body as expected, so the regex is having trouble to do its job. Thus,
- Given that no project was present prior to the changes in PR #72, the bug was already there before them.
- I had tested the regex when doing PR #55 (cross-referencing https://github.com/brainhackorg/global2021/pull/32#issuecomment-932805057), but maybe when testing on the issues in your fork the body of the issue changed slightly to just make the regex work.

**Comment by Remi-Gau** [comment]
Thanks for the detailed explanation @jhlegarreta.

BTW:  I did not mean to imply you had overlooked something.
